# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
matrix:
  include:
    - python: 2.7
      env: TESTENV=docs
  exclude:
    - python: 2.6
    - python: 3.3
    - python: 3.4
    - python: 3.5
addons:
  apt:
    packages:
    - python-numpy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
